name: Speedrun
version: '1.0'
main: net.smprun.speedrun.Speedrun
api-version: '1.21'
description: SMPRun Network speedrun plugin
website: https://smprun.net
authors:
  - memheap
folia-supported: true

dependencies:
  server:
    Common:
      load: BEFORE
      required: true
      join-classpath: true

permissions:
  speedrun.freeze.bypass:
    description: Bypass pre-game freeze and allow movement before game starts
    default: op
  speedrun.chat.bypass:
    description: Bypass global chat mute enforced by the Speedrun plugin
    default: op