name: Speedrun
version: '1.0'
main: net.smprun.speedrun.Speedrun
api-version: '1.21'
description: SMPRun Network speedrun plugin
website: https://smprun.net
authors:
  - memheap
folia-supported: true

dependencies:
  server:
    Common:
      load: BEFORE
      required: true
      join-classpath: true